//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anclaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Anclaje()
        {
            this.Viajes = new HashSet<Viaje>();
            this.Viajes1 = new HashSet<Viaje>();
        }
    
        public int idEstacion { get; set; }
        public int id { get; set; }
        public string idBici { get; set; }
        public Anclaje(int idEstacion, int id, string idBici)
        {
            this.idEstacion = idEstacion;
            this.id = id;
            this.idBici = idBici;
        }
        public virtual Bicicleta Bicicleta { get; set; }
        public virtual Estacion Estacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Viaje> Viajes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Viaje> Viajes1 { get; set; }
    }
}
