//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Viajes = new HashSet<Viaje>();
        }

        public Usuario(string email, string contrasena, int telefono, string numCuenta, double monedero)
        {
            this.email = email;
            this.contrasena = contrasena;
            this.telefono = telefono;
            this.numCuenta = numCuenta;
            this.monedero = monedero;
        }

        public int id { get; set; }
        public string email { get; set; }
        public string contrasena { get; set; }
        public int telefono { get; set; }
        public string numCuenta { get; set; }
        public double monedero { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Viaje> Viajes { get; set; }
    }
}
